### ISSUE TITLE
text-codec.js is not included in npm files/ list in package.json

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/minimal-jwt#2]
Currently, the `files:` property in `package.json` lists each file individually (and `text-codec.js` is missing from it).

To fix, let's move all the js files that need inclusion into the lib/ folder as usual.

**Comment by davidlehn** [comment]
This can be closed.  Note that when not being explicit with the files you tradeoff with the need to be careful when publishing so as not to let temporary editor files or other cruft get in the releases.
